name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: ['**']

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
        target: [x86_64, x86, aarch64]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
      - uses: baptiste0928/cargo-install@v2
        with:
          crate: xwin
      - name: Run xwin
        if: (startsWith(matrix.runs-on, 'windows')) || (startsWith(matrix.runs-on, 'macos'))
        run: xwin --arch=${{ matrix.target }} --accept-license splat --output $PWD/.xwin --include-debug-symbols --preserve-ms-arch-notation --disable-symlinks --include-debug-libs
      - name: Run xwin (linux only)
        if: startsWith(matrix.runs-on, 'ubuntu')
        run: xwin --arch=${{ matrix.target }} --accept-license splat --output $PWD/.xwin --include-debug-symbols --preserve-ms-arch-notation --include-debug-libs

      - name: build summary
        run: zig build --summary all -freference-trace -Doptimize=ReleaseFast -Dtarget=${{ matrix.target }}-windows-msvc
