name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      - uses: baptiste0928/cargo-install@v2
        with:
          crate: xwin
      - name: Run xwin
        run: xwin --accept-license splat --output $PWD/.xwin --include-debug-symbols --preserve-ms-arch-notation --include-debug-libs

      - name: build summary
        run: zig build --summary all -freference-trace -Dtarget=x86_64-windows-msvc
