name: Build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      - uses: baptiste0928/cargo-install@v2
        with:
          crate: xwin
      - name: Run xwin
        run: xwin --accept-license splat --output $PWD/.xwin --disable-symlinks --include-debug-libs && rm -rf .xwin-cache

      - name: build summary
        run: zig build --summary all -freference-trace -Dtarget=x86_64-windows-msvc